version = "2"

[linters]
default = 'all'
disable = [
    'depguard',
    'gomoddirectives',
    'ireturn',
    'musttag',
    'nlreturn',
    'recvcheck',
    'sqlclosecheck',
    'wsl',
]
enable = [
    "revive",
]

[linters.settings]
[linters.settings.tagliatelle]
[linters.settings.tagliatelle.case]
[linters.settings.tagliatelle.case.rules]
envconfig = 'upperSnake'
json = 'snake'

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = "var-naming"
disabled = true

[[linters.settings.revive.rules]]
name = "file-length-limit"

[[linters.settings.revive.rules.arguments]]
max = 1500
skip-comments = false
skip-blank-lines = false
[linters.settings.varnamelen]
ignore-names = ['rx', 'tx', 'db', 'ok', 'mw', 'gw', 'rt', 'id']
ignore-decls = ['w http.ResponseWriter', 'r *http.Request', 'g *Gateway']

[linters.settings.wsl_v5]
allow-first-in-block = true
branch-max-lines = 2
allow-whole-block = false
disable = ["decl"]

[linters.exclusions]
generated = 'lax'
presets = ['comments', 'common-false-positives', 'legacy', 'std-error-handling']
paths = ['third_party$', 'builtin$', 'examples$']

[[linters.exclusions.rules]]
linters = ['gosec']
text = 'G601:'

[[linters.exclusions.rules]]
linters = ['errcheck']
text = 'viper.Bind'

[[linters.exclusions.rules]]
linters = ['mnd']
source = 'cobra.MinimumNArgs'

[[linters.exclusions.rules]]
linters = ['gochecknoglobals', 'gochecknoinits']
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = ['err113', 'wrapcheck']
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = ['godot']
source = '^//+\s*language=\S+\s*$'

[severity]
default = 'warn'

[[severity.rules]]
linters = ['exhaustive', 'exhaustruct', 'godox']
severity = 'info'

[formatters]
enable = ['gci', 'gofumpt', 'goimports']

[formatters.exclusions]
generated = 'lax'
paths = ['third_party$', 'builtin$', 'examples$']
